version: "3.8"

services:
  mariadb:
    image: mariadb:11
    container_name: studyplanner-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: studyplanner 
      MARIADB_USER: studyuser
      MARIADB_PASSWORD: studypass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
